flowchart LR
    dev@{ label: "<img src=\"https://api.iconify.design/fa6-solid/user-gear.svg\" width=\"26\"><br>Dev" } --> pr["Pull&nbsp;Request"]
    pr --> repo@{ label: "<img src=\"https://api.iconify.design/octicon/repo.svg\" width=\"28\"><br>GitOps&nbsp;Repo" }
    repo --> ci@{ label: "<img src=\"https://api.iconify.design/logos/github-actions.svg\" width=\"28\"><br>CI&nbsp;Workflow" }
    ci --> opa{"<br>OPA<br>PolicyGate"}
    opa -- pass --> merge["Merge"]
    merge --> argo@{ label: "<img src=\"https://api.iconify.design/simple-icons/argo.svg\" width=\"24\"><br>ArgoCD&nbsp;Sync" }
    argo --> cluster@{ label: "<img src=\"https://api.iconify.design/logos/kubernetes.svg\" width=\"30\"><br>K8s" }
    cluster --> gk@{ label: "<img src=\"https://api.iconify.design/material-icon-theme:opa.svg\" width=\"24\"><br>Gatekeeper" }

    dev@{ shape: rect}
    repo@{ shape: rect}
    ci@{ shape: rect}
    argo@{ shape: rect}
    cluster@{ shape: rect}
    gk@{ shape: rect}
     cluster:::blue
    classDef blue fill:#e3f2fd,stroke:#1e88e5,stroke-width:2px,radius:4px
    classDef pink fill:#fce4ec,stroke:#d81b60,stroke-width:2px,radius:4px
