flowchart LR
    classDef header fill:none,stroke:none,font-size:22px,font-weight:bold,text-align:center
    daas["GitOps Flow – OPA Policy Gate"]:::header

    dev["<img src='https://api.iconify.design/fa6-solid/code-compare.svg' width='34'><br/>Pull&nbsp;Request"]
    repo["<img src='https://api.iconify.design/mdi/source-repository.svg' width='38'><br/>Git&nbsp;Repo"]
    action["<img src='https://api.iconify.design/logos/github-icon.svg' width='38'><br/>CI&nbsp;Action"]
    opa["<img src='https://api.iconify.design/simple-icons/openpolicyagent.svg' width='38'><br/>OPA&nbsp;Conftest"]
    argo["<img src='https://api.iconify.design/logos/argocd-icon.svg' width='40'><br/>ArgoCD"]
    k8s["<img src='https://api.iconify.design/logos/kubernetes.svg' width='40'><br/>Cluster"]

    dev --> repo --> action --> opa --> argo --> k8s
